### ISSUE TITLE
AUR: FINISHED

### ISSUE THREAD

**Issue by FadeMind** [PapirusDevelopmentTeam/STAFF#1]
@varlesh 
Migration packages to AUR is DONE.
Mirror of current AUR PKGBUILDs is here: https://github.com/PapirusDevelopmentTeam/PKGBUILDs

**Comment by varlesh** [comment]
@FadeMind Great job, it's fine )) Please see https://github.com/PapirusDevelopmentTeam/PKGBUILDs/issues/1

**Comment by FadeMind** [comment]
@varlesh I am maintainer both versions of papirus and papirus-git. 
@horosgrisa is not maintainer any more. He left self.

**Comment by FadeMind** [comment]
@varlesh All is done. Feedback is welcome.
https://github.com/PapirusDevelopmentTeam/PKGBUILDs

**Comment by varlesh** [comment]
Very good, it's all ok ))
