### ISSUE TITLE
hi :)

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/STAFF#7]
@FadeMind Add me on team. I'm have update for icons

**Comment by varlesh** [comment]
@azadaquib Hi. Thx for your work, i seen you add new icons - it's very good )))

**Comment by varlesh** [comment]
I'm add [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) support

**Comment by varlesh** [comment]
@azadaquib Please add me on PapirusDevelopmentTeam

**Comment by FadeMind** [comment]
Done.

**Comment by varlesh** [comment]
Thx Tomasz :)

**Comment by azadaquib** [comment]
@varlesh Thanks :)

**Comment by varlesh** [comment]
@azadaquib i'm fixed only icons

**Comment by varlesh** [comment]
Papirus icons now support https://github.com/bil-elmoussaoui/Hardcode-Tray I'm delete some extra-icons, because not needed anymore (this icons moved on status and used with Hardcode-Tray)

**Comment by FadeMind** [comment]
@varlesh  you are now owner. I leave this team now.

Regards

**Comment by varlesh** [comment]
Ok. Thx for help and your work!

**Comment by varlesh** [comment]
@FadeMind You discontinue support PKGBUILD's?

**Comment by FadeMind** [comment]
@varlesh  See https://www.reddit.com/r/kde/comments/55pczr/papirus_suite_kde_i_want_to_give_the_whole/

I disowned PKGBUILD's some time ago. I don't have time for maintain.

**Comment by varlesh** [comment]
It is a pity :( of course, but development can not continue indefinitely. I do not have much time to devote to projects. My commits temporrary. I cant' have full time for Papirus and other projects.
Thank you for your work and patience. With you it was good to develop our project.
Maybe @azadaquib and other people continue development...

**Comment by azadaquib** [comment]
I will be here as long as I can be. I will try to do better commits and not screw up. That's all :)

**Comment by varlesh** [comment]
Big thx @azadaquib !

**Comment by varlesh** [comment]
@azadaquib What OS and DE you use?

**Comment by azadaquib** [comment]
@varlesh I use Ubuntu 16.10 with Unity.

**Comment by varlesh** [comment]
ok. I'm KDE Neon  now

**Comment by azadaquib** [comment]
I will probably install KDE neon along. :)

**Comment by varlesh** [comment]
I can't find this icons for Pantheon Mail
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk/issues/53

**Comment by azadaquib** [comment]
That's the recycle bin icon. Somehow its using the recycle bin icon. Maybe we can revert back to the old simple grey and red recycle bin icons that were there before you redesigned them...

**Comment by varlesh** [comment]
No, i found icon for "red flag", maybe this "edit-mark" and "Важное"

**Comment by azadaquib** [comment]
![screenshot from 2016-10-25 19-32-15](https://cloud.githubusercontent.com/assets/8470127/19689152/01d17824-9aea-11e6-9b0d-f8208ee80e16.png)
For me its fine...

**Comment by varlesh** [comment]
Pantheon Mail - it's patched Geary (with other icons) from elementary PPA:
https://launchpad.net/~elementary-os/+archive/ubuntu/stable

**Comment by varlesh** [comment]
Geary use symbolic icons
